//
//  Sentences.swift
//  DRINKING
//
//  Created by Adrià Sala Roget on 06/06/2020.
//  Copyright © 2020 Adrià Sala Roget. All rights reserved.
//

import Foundation

struct Sentences {
    
    static let yoNunca = [
        "...he robado en una tienda.",
        "...he pegado a alguien.",
        "...he mandado una foto caliente.",
        "...he hecho un trio.",
        "...he tenido un calentón en clase.",
        "...he tenido sexo en público.",
        "...me he arrastrado por alguien.",
        "...me he he hecho una foto caliente.",
        "...he hecho sexting.",
        "...me he sentido atraídx por alguno de los presentes.",
        "...me he liado con alguno de los presentes.",
        "...he bebido en el cole.",
        "...he ido morado al cole.",
        "...he tenido una relación de más de dos años.",
        "...he hecho un trío.",
        "...me he liado con alguien de mi mismo sexo.",
        "...he sido infiel.",
        "...me he inventado que me he liado o he tenido sexo con alguien.",
        "...me he liado con un/a amigx por diversión.",
        "...me he liado con alguien más pequeño que yo.",
        "...me he liado con más de tres en una noche.",
        "...he hecho una orgía.",
        "...he hecho un cambio de pareja.",
        "...he sentido atracción por un/a profesor/a.",
        "...me liaría con alguno de los presentes.",
        "...he mentido en un yo nunca.",
        "...he hecho una cobra.",
        "...me han hecho una cobra.",
        "...me he enamorado.",
        "...he echado por culpa del alcohol.",
        "...me he mirado en el espejo y he pensado que estoy muy buenx.",
        "...he hecho una iguana (pasarse el humo).",
        "...me he sentido atraído por alguien de mi mismo sexo.",
        "...he pensado que me tiraría a un padre/madre.",
        "...me he liado con alguien sin saber su nombre.",
        "...he tenido sexo en la playa.",
        "...he hecho posiciones del kamasutra (conscientemente).",
        "...me he hecho a la pareja de un/a amigx.",
        "...me han echado de una discoteca.",
        "...me he tirado a un padre/madre.",
        "...me he tirado al ex o a la ex de un/a amigx.",
        "...lo he hecho a pelo.",
        "...he jugado con los sentimientos de alguien.",
        "...me he escapado de casa.",
        "...he utilizado la misma ropa interior dos días seguidos.",
        "...he tenido una cita a ciegas.",
        "...me he colado en una fiesta.",
        "...he ido al cole en pijama.",
        "...he tenido dos citas en un mismo día.",
        "...se me ha caído el móvil al váter.",
        "...he sido perseguido por la poli.",
        "...he tenido sexo anal.",
        "...me he tirado a alguien en el cole.",
        "...he usado juguetes sexuales.",
        "...me he grabado teniendo sexo.",
        "...me han pillado follando.",
        "...he tragado semen.",
        "...se me han corrido en la cara.",
        "...he o me han masturbado con los pies.",
        "...he tenido pedos vaginales.",
        "...me he tirado un pedo mientras follaba.",
        "...he follado con gente en casa.",
        "...he tenido sexo en casa de un/a amigx.",
        "...he perdido la virginidad borrachx.",
        "...he fingido un orgasmo.",
        "...me he desnudado en público.",
        "...he tenido sexo en el coche.",
        "...me he masturbado en el coche.",
        "...he tenido un sueño erótico con alguno de los presentes.",
        "...he compartido saliva con alguno de los presentes.",
        "...he pillado a mis padres follando.",
        "...lo he hecho en los baños de una discoteca.",
        "...lo he hecho en un baño público.",
        "...me he liado con alguien con pareja.",
        "...me he tirado a alguien con pareja.",
        "...me he hecho al hermano/a de un/a amigx.",
        "...he pagado por sexo.",
        "...he probado las drogas.",
        "...me he masturbado más de 5 veces en un día.",
        "...he / me han hecho una cubana.",
        "...he tenido un gatillazo.",
        "...he pensado que el tamaño importa.",
        "...he follado moradx.",
        "...he conducido borrachx.",
        "...me ha pillado un coma etílico.",
        "...me he liado después de potar.",
        "...he / me han hecho un beso negro.",
        "...he pillado a un/a amigx follando.",
        "...he hecho el trío del diablo.",
        "...he mirado porno con alguien.",
        "...me he masturbado con alguien.",
        "...me he liado con alguien 5 años más mayor que yo.",
        "...he hecho un bucaque.",
        "...he vendido drogas.",
        "...he pensado en otra persona mientras follaba con alguien.",
        "...he follado en medio de una pelea con mi pareja.",
        "...he hecho un trío del diablo (2 tíos min.).",
        "...he pensado que soy el/la más guapx de mi grupo de amigos.",
        "...he pensado que soy la persona que va a tener más éxito en la vida de mi grupo de amigos.",
        "...me he disfrazado del género contrario para follar.",
        "...me he masturbado mientras conducía.",
        "...he desvirgado a alguien",
        "...he mirado si mi signo del zodiaco y el de mi crush eran compatibles",
        "...he visto hentai.",
        "...he salido en televisión",
        "...le he petado una espinilla a otra persona",
        "...me he maquillado",
        "...he hecho drag",
        "...he dudado de mi identidad de género",
        "...he mentido para intentar gustarle más a mi crush",
        "...me he declarado a alguien",
        "...he hecho ghosting",
        "...he pagado por porno",
        "...he subido un video erótico a internet",
        "...he guardado los nudes de alguien después de haber roto con ellos"
    ]
    
    static let back2back = [
        "...la chupa mejor.",
        "...besa mejor.",
        "...la tiene más grande.",
        "...está más buenx.",
        "...tiene mejor culo",
        "...sería mejor sugar baby",
        "...se haría sugar daddy/mommy",
        "...aguanta más el alcohol",
        "...perrea mejor",
        "...perrea más sucio",
        "...ganaría más dinero como stripper",
        "...es más fácil",
        "...es más perra",
        "...aguanta más tiempo follando",
        "...conseguiría seducirme antes",
        "...ha ligado con más personas de esta sala",
        "...es peor borracho",
        "...tira más ficha por redes sociales",
        "...usa el instagram más para ligar",
        "...puede imitar mejor a un mono",
        "...se disfrazaría de la cosa más rara para follar",
        "...se liaría con la persona más mayor",
        "...le ha hecho sexo oral a más gente",
        "...disfruta más haciendo sexo oral",
        "...gime más raro",
        "...grita más en la cama",
        "...ha sido más cabrón con un ex",
        "...tiene el fetiche más raro",
        "...hace menos que ha visto porno",
        "...se sabe de memoria más canciones de reggaeton",
        "...deja más marcas follando",
        "...es más arrítmico follando",
        "...estaría más guapo/a con las cejas afeitadas",
        "...se teñiría el pelo púbico",
        "...es más romántico",
        "...tiene el pelo más bonito",
        "...ganaría en una pelea",
        "...puede beber más chupitos en una noche",
        "...tiene peor gusto para las parejas",
        "...tiene peor gusto musical",
        "...ha fingido más orgasmos",
        "...ha tragado más semen",
        "...es más dramas",
        "...ha tenido más lios de una noche"

    ]
    
    static let prefiero = [
        "...besar a un hombre o a una mujer.",
        "...beber ron o vodka.",
        "...coño o polla.",
        "...comerme un coágulo de sangre de la regla o una lenteja",
        "...no volver a perrear o no volver a beber alcohol",
        "...enviar un nude a tu madre o a tu padre",
        "...recibir un nude de tu madre o de tu padre",
        "...recibir un nude de tu crush en la vida real o de tu crush famoso",
        "...no volver a vomitar por borracho o no volver a tener resaca",
        "...no volver a escuchar reggaeton o no volver a comer pizza",
        "...tirarte a tu crush famoso o a tu crush de la vida real",
        "...ir a OT o a Gran Hermano",
        "...Rosalía o Bad Gyal",
        "...hacer roleplay o bondage",
        "...ser dominante o sumiso",
        "...que te azoten o que te ahoguen ",
        "...hablar sucio o que me hablen sucio",
        "...tirarte a un amigo cercano o a un desconocido",
        "...tirarte al ex de un/a amigo/a o al hermano/a de un/a amigo/a",
        "...anal o oral",
        "...morder o hacer un chupeton",
        "...yogurines o maduritxs",
        "...follar en la cama o contra una mesa",
        "...operarse el culo o los labios",
        "...depilarte las cejas o las piernas",
        "...tener un hijo o un perro",
        "...tirarme a la persona de mi izquierda o de mi derecha",
        "...tirarte a un/a amigo/a de tu padre o a un padre/madre de un amigo",
        "...tirarte a tu primo/a sin saber que sois familia, o tirarte a un/a primo/a segundo sabiendo quien es",
        "...que te muerdan o te aten",
        "...que te amordacen o te venden los ojos",
        "...tirarte a tu jefe o a un trabajador subordinado",
        "...voyeurismo o exhibicionismo",
        "...beber o fumar"
    ]
    
    static let quienEsMasProbable = [
        "...que tenga un juguete sexual.",
        "...que haya tenido sexo esta semana.",
        "...que triunfe esta noche.",
        "...que eche la pota.",
        "...que folle mejor",
        "...que tenga nudes propios en su galería",
        "...que haya hecho ghosting",
        "...que use Tinder solo para subirse la autoestima",
        "...que se tire a Santiago Abascal",
        "...que se tire a alguien y se arrepienta a la mañana siguiente",
        "...que envíe un screenshot de la conversación a la misma persona con la que habla",
        "...que esté tirando ficha a más gente ahora mismo",
        "...que cante mientras folla",
        "...que se lesione follando",
        "...que se haga actor/actriz porno",
        "...que tenga la fantasía sexual más rara",
        "...que se masturbe más",
        "...que se sienta sexualmente atraído por un Teletubbie",
        "...que se convierta en un sugarbaby",
        "...que contrate a un sugarbabys",
        "...que se ponga malo por comerse algo caducado",
        "...que sea un furry",
        "...que se abra un onlyfans",
        "...que se tire a dos hermanos/as",
        "...que se haga una operación estética",
        "...que se tire al hermano/a de un amigo",
        "...que acosando a alguien por redes sociales, le de like a una foto de hace meses",
        "...que se tire a alguien 10 años mayor",
        "...que se tire a alguien menor de 18 años",
        "...que folle disfrazado de Winnie de Pooh",
        "...que tenga un fetiche con los antebrazos",
        "...que haya dejado a más gente con el calentón",
        "...que se haga un corte de pelo del que se arrepienta el resto de su vida",
        "...que se tatue el culo",
        "...que stalkee a un/a crush por redes sociales",
        "...que pegase a uno de los presentes",
        "...que su Jonas Brother favorito fuera Kevin",
        "...que prefiera Camp Rock a High School Musical",
        "...que perdiera en una pelea contra un niño de cuatro años",
        "...que se rape al cero",
        "...que se divorcie tres veces",
        "...que caiga en un timo",
        "...que haya sido el crush de más personas de esta sala",
        "...que tenga el peor gusto en parejas",
        "...que se haya comprado más juguetes sexuales",
        "...que se sepa más canciones Disney de memoria",
        "...que se tirara a alguien que tiene pareja sabiéndolo",
        "...que suba una historia a instagram para que le conteste una persona en particular",
        "...que se la chupe a alguien del barrio",
        "...que vuelva con su ex",
        "...que se haga famoso",
        "...que sea millonario",
        "...que lo multen por follar en público",
        "...que se meta en una secta satánica y sea el sacrificado",
        "...que se tire al padre/madre de uno de los presentes",
        "...que mate a uno de los presentes sin querer",
        "...que se lie con el ex de uno de los presentes",
        "...que tenga un hijo no deseado",
        "...que se case antes",
        "...que le de un coma etílico",
        "...que le detenga la policía",
        "...que se case por un visado",
        "...que se meta a monja/cura",
        "...que le pillen follando",
        "...que ponga los cuernos",
        "...que se quede soltero/a para siempre",
        "...que tenga más hijos",
        "...que se muera antes",
        "...que se pelee de fiesta"
    ]
    
}
